openapi: 3.0.0
info:
  title: Totality Percepts API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/percepts/{type}/locale/{locale}':
    parameters:
      - schema:
          type: string
        name: type
        in: path
        required: true
      - schema:
          type: string
        name: locale
        in: path
        required: true
    get:
      summary: Retrieve percepts by locale
      tags:
        - perceive
      responses: {}
      operationId: get-percepts-type-locale-locale
components:
  schemas: {}
