openapi: 3.0.0
info:
  title: Totality Observation API
  version: '1.0'
  contact:
    name: Beau Cronin
    email: beau.cronin@gmail.com
  description: API endpoints for submitting new or updated observations of Totality nodes and readings
servers:
  - url: 'http://localhost:3000'
paths:
  '/observations/readings/{node_type}/{type_id}':
    parameters:
      - schema:
          type: string
        name: node_type
        in: path
        required: true
      - schema:
          type: string
        name: type_id
        in: path
        required: true
    post:
      summary: Submit a reading
      tags:
        - observe
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      operationId: post-readings-node_type-type_id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/ReadingObservations.v1.yaml
      description: Submit a new or updated reading
      security:
        - API Key - 1: []
  /observations/nodes:
    post:
      summary: Create or update one or more nodes
      tags:
        - observe
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      operationId: post-nodes
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/NodeObservations.v1.yaml
        description: ''
      parameters: []
      description: Submit a new or updated node
      security:
        - API Key - 1: []
    parameters: []
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: X-Api-Key
      type: apiKey
      in: header
